const starter=[
["adult","成年人"],["baby","婴儿"],["boy","男孩"],["girl","女孩"],["child","孩子"],["children","孩子们"],["family","家庭"],["parent","父亲或母亲"],["mother","母亲"],["father","父亲"],["brother","兄弟"],["sister","姐妹"],["son","儿子"],["daughter","女儿"],["grandfather","祖父；外祖父"],["grandmother","祖母；外祖母"],["husband","丈夫"],["wife","妻子"],["friend","朋友"],["neighbour","邻居"],["guest","客人"],["person","人"],["people","人们"],["student","学生"],["teacher","老师"],["classmate","同学"],["doctor","医生"],["nurse","护士"],["driver","司机"],["farmer","农民"],
["house","房子"],["home","家"],["room","房间"],["bedroom","卧室"],["bathroom","浴室"],["kitchen","厨房"],["garden","花园"],["floor","地板；楼层"],["door","门"],["window","窗户"],["wall","墙"],["table","桌子"],["chair","椅子"],["bed","床"],["desk","书桌"],["cupboard","橱柜"],["shelf","架子"],["mirror","镜子"],["lamp","灯"],["key","钥匙"],["shower","淋浴"],["towel","毛巾"],["brush","刷子；刷"],["soap","肥皂"],["clock","时钟"],["television","电视"],["computer","电脑"],["phone","电话"],["internet","互联网"],["address","地址"],
["school","学校"],["classroom","教室"],["lesson","课"],["subject","科目"],["homework","家庭作业"],["course","课程"],["exam","考试"],["question","问题"],["answer","答案；回答"],["example","例子"],["exercise","练习；锻炼"],["book","书"],["page","页"],["paper","纸；试卷"],["pen","钢笔"],["pencil","铅笔"],["ruler","尺子"],["dictionary","词典"],["language","语言"],["English","英语"],["maths","数学"],["science","科学"],["history","历史"],["geography","地理"],["music","音乐"],["art","美术"],["office","办公室"],["job","工作；职业"],["work","工作"],["holiday","假期"],
["town","城镇"],["city","城市"],["village","村庄"],["country","国家；乡村"],["street","街道"],["road","道路"],["bridge","桥"],["station","车站"],["airport","机场"],["hotel","酒店"],["restaurant","餐馆"],["café","咖啡馆"],["shop","商店"],["supermarket","超市"],["market","市场"],["bank","银行"],["hospital","医院"],["library","图书馆"],["museum","博物馆"],["cinema","电影院"],["theatre","剧院"],["park","公园"],["beach","海滩"],["mountain","山"],["river","河流"],["lake","湖"],["sea","海"],["bus","公共汽车"],["train","火车"],["bicycle","自行车"],
["breakfast","早餐"],["lunch","午餐"],["dinner","晚餐"],["meal","一餐"],["food","食物"],["drink","饮料；喝"],["water","水"],["milk","牛奶"],["juice","果汁"],["tea","茶"],["coffee","咖啡"],["bread","面包"],["rice","米饭"],["pasta","意大利面"],["meat","肉"],["chicken","鸡肉；鸡"],["fish","鱼"],["egg","鸡蛋"],["cheese","奶酪"],["fruit","水果"],["apple","苹果"],["banana","香蕉"],["orange","橙子"],["vegetable","蔬菜"],["potato","土豆"],["tomato","西红柿"],["cake","蛋糕"],["sandwich","三明治"],["bottle","瓶子"],["menu","菜单"],
["time","时间"],["day","天"],["week","星期"],["month","月"],["year","年"],["morning","早晨"],["afternoon","下午"],["evening","傍晚"],["night","夜晚"],["today","今天"],["tomorrow","明天"],["yesterday","昨天"],["weekend","周末"],["spring","春天"],["summer","夏天"],["autumn","秋天"],["winter","冬天"],["weather","天气"],["sun","太阳"],["rain","雨；下雨"],["snow","雪；下雪"],["wind","风"],["cloud","云"],["hot","热的"],["cold","冷的"],["tree","树"],["flower","花"],["animal","动物"],["dog","狗"],["cat","猫"],
["body","身体"],["head","头"],["face","脸"],["hair","头发"],["eye","眼睛"],["ear","耳朵"],["nose","鼻子"],["mouth","嘴"],["hand","手"],["arm","胳膊"],["leg","腿"],["foot","脚"],["back","背部"],["heart","心脏"],["health","健康"],["ill","生病的"],["sick","生病的"],["medicine","药"],["clothes","衣服"],["shirt","衬衫"],["T-shirt","T恤"],["trousers","裤子"],["dress","连衣裙"],["skirt","短裙"],["shoe","鞋"],["coat","外套"],["jacket","夹克"],["hat","帽子"],["bag","包"],["glasses","眼镜"],
["be","是；成为"],["have","有"],["do","做"],["make","制作"],["get","得到；到达"],["give","给"],["take","拿；带"],["bring","带来"],["buy","购买"],["pay","付款"],["choose","选择"],["find","找到"],["look","看"],["see","看见"],["watch","观看"],["hear","听见"],["listen","听"],["speak","说话"],["say","说"],["tell","告诉"],["ask","询问"],["reply","回复"],["read","阅读"],["write","写"],["spell","拼写"],["learn","学习"],["study","学习；研究"],["teach","教"],["know","知道"],["remember","记住"],["understand","理解"],["think","思考；认为"],["want","想要"],["need","需要"],["like","喜欢"],["love","喜爱"],["prefer","更喜欢"],["help","帮助"],["use","使用"],["practice","练习"],["play","玩；演奏"],["go","去"],["come","来"],["arrive","到达"],["leave","离开"],["travel","旅行"],["visit","参观；拜访"],["meet","遇见"],["live","居住"],["stay","停留"],["eat","吃"],["wash","洗"],["cook","烹饪"],["open","打开"],["close","关闭"],["start","开始"],["finish","完成"],["wait","等待"],["wear","穿；戴"],["carry","携带"],
["good","好的"],["bad","坏的"],["big","大的"],["small","小的"],["long","长的"],["short","短的"],["new","新的"],["old","旧的；年老的"],["young","年轻的"],["beautiful","美丽的"],["important","重要的"],["interesting","有趣的"],["exciting","令人兴奋的"],["boring","无聊的"],["difficult","困难的"],["easy","容易的"],["different","不同的"],["same","相同的"],["happy","高兴的"],["sad","伤心的"],["tired","疲倦的"],["busy","忙碌的"],["free","空闲的；免费的"],["early","早的"],["late","迟的"],["fast","快的"],["slow","慢的"],["careful","小心的"],["friendly","友好的"],["ready","准备好的"]
].map(([en,zh])=>({en,zh,mastered:0,mistakes:0}));
const modes=[{id:"listen",icon:"♫",title:"听音选义",note:"听懂它"},{id:"meaning",icon:"EN",title:"看义选词",note:"认出它"},{id:"spell",icon:"⌨",title:"拼写挑战",note:"写对它"},{id:"read",icon:"●",title:"跟读闪卡",note:"读准它"}];
const load=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))||f}catch{return f}};
const savedWords=load("word-quest-words",starter),wordsToUse=savedWords.length===30&&savedWords.some(w=>w.en==="adventure")&&savedWords.some(w=>w.en==="wonderful")?starter:savedWords;
const S={words:wordsToUse,view:"home",mode:"listen",round:[],index:0,choices:[],answer:"",feedback:"",score:0,streak:0,best:load("word-quest-stats",{best:0}).best||0,lives:3,showImport:false,soundOn:true};
const app=document.querySelector("#app"),shuffle=a=>[...a].sort(()=>Math.random()-.5),cur=()=>S.round[S.index];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
function save(){localStorage.setItem("word-quest-words",JSON.stringify(S.words));localStorage.setItem("word-quest-stats",JSON.stringify({best:S.best}))}
function parseWords(text){return text.split("\n").map(x=>x.trim()).filter(Boolean).map(line=>{const p=line.split(/[,，\t:：|]+/).map(x=>x.trim()).filter(Boolean);return p.length>=2?{en:p[0],zh:p.slice(1).join("，"),mastered:0,mistakes:0}:null}).filter(Boolean)}
function speak(word){if(!S.soundOn||!word||!("speechSynthesis" in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(word);u.lang="en-GB";u.rate=.82;speechSynthesis.speak(u)}
function choices(target,mode){return ["spell","read"].includes(mode)?[]:shuffle([target,...shuffle(S.words.filter(w=>w.en!==target.en)).slice(0,3)])}
function header(){return `<header class="topbar"><button class="brand" data-act="home"><span>WQ</span><b>WORD QUEST<small>KET 词汇大冒险</small></b></button><nav><button class="${S.view==="home"?"active":""}" data-act="home">游戏大厅</button><button class="${S.view==="words"?"active":""}" data-act="words">我的词库</button></nav><div class="header-stats"><span>🏆 最佳连胜 <b>${S.best}</b></span><button class="sound" data-act="sound">${S.soundOn?"🔊":"🔇"}</button></div></header>`}
function home(){const mastered=S.words.filter(w=>w.mastered>=3).length,learned=S.words.filter(w=>w.mastered>0).length;return `<div class="shell home"><section class="hero"><div><span class="eyebrow">今日任务 · ${S.words.length} 个单词已就位</span><h1>玩一局，<em>记住十个词。</em></h1><p>每局随机抽词，听、认、拼、读轮番挑战。错词会悄悄提高出现频率。</p></div><div class="score-card"><span>本机学习进度</span><strong>${mastered}<small> / ${S.words.length}</small></strong><div class="meter"><i style="width:${S.words.length?mastered/S.words.length*100:0}%"></i></div><small>已牢固掌握 · 每词答对 3 次</small></div></section><section class="mode-grid">${modes.map((m,i)=>`<button class="mode-card c${i}" data-mode="${m.id}"><span class="mode-icon">${m.icon}</span><span class="mode-copy"><small>关卡 0${i+1} · ${m.note}</small><b>${m.title}</b><em>开始挑战 →</em></span></button>`).join("")}</section><section class="dashboard"><div class="panel mission"><div class="panel-title"><b>本周任务</b><span>坚持就是超能力</span></div><div class="days">${["一","二","三","四","五","六","日"].map((d,i)=>`<div class="${i<3?"done":i===3?"today":""}"><span>${i<3?"✓":i===3?"▶":"·"}</span><small>周${d}</small></div>`).join("")}</div></div><div class="panel quick"><div><span>⚡</span><p><b>极速混合赛</b><small>四种题型随机出现</small></p></div><button data-act="quick">来一局</button></div><div class="panel stat"><span>已遇见</span><b>${learned}</b><small>个单词</small></div></section><button class="parent-entry" data-act="import">⚙ 家长：更换本周词库</button></div>`}
function wordList(){return `<div class="shell words-view"><div class="words-head"><div><span class="eyebrow">家长控制台</span><h1>本周词库</h1><p>点击发音试听；答对 3 次的单词会标记为“已掌握”。</p></div><button data-act="import">＋ 更换词库</button></div><div class="word-table">${S.words.map((w,i)=>`<div><span>${String(i+1).padStart(2,"0")}</span><button data-speak="${esc(w.en)}">🔊</button><b>${esc(w.en)}</b><em>${esc(w.zh)}</em><i class="${w.mastered>=3?"mastered":""}">${w.mastered>=3?"已掌握":`${w.mastered}/3`}</i></div>`).join("")}</div></div>`}
function game(){const w=cur(),progress=(S.index+1)/S.round.length*100,accuracy=S.index?Math.round(S.score/(S.index*100)*100):100;const prompt=S.mode==="listen"?"听一听，这个单词是什么意思？":S.mode==="meaning"?`哪个单词表示“${esc(w.zh)}”？`:S.mode==="spell"?`请拼出“${esc(w.zh)}”`:"先听，再大声读三遍";let task=S.mode==="listen"?`<button class="speaker" data-speak="${esc(w.en)}"><span>▶</span><b>播放单词</b><small>可以反复听</small></button>`:S.mode==="meaning"?`<div class="word-prompt">${esc(w.zh)}</div>`:S.mode==="spell"?`<div class="spell-box"><button data-speak="${esc(w.en)}">🔊</button><input id="spell" value="${esc(S.answer)}" placeholder="在这里输入英文单词" spellcheck="false"><button class="submit" data-act="spell">确认</button></div>`:`<div class="read-card"><button data-speak="${esc(w.en)}">🔊</button><strong>${esc(w.en)}</strong><span>${esc(w.zh)}</span><p>听清重音和音节，然后大声读出来</p><button class="read-done" data-act="readDone">我已经读了 3 遍</button></div>`;const opts=["listen","meaning"].includes(S.mode)?`<div class="choices">${S.choices.map((c,i)=>`<button data-choice="${esc(c.en)}"><kbd>${i+1}</kbd>${S.mode==="listen"?esc(c.zh):esc(c.en)}</button>`).join("")}</div>`:"";const fb=S.feedback?`<div class="feedback"><span>${S.feedback==="right"?"✓":"×"}</span><div><b>${S.feedback==="right"?"答对了！太棒啦":"差一点，再记一次"}</b><p><strong>${esc(w.en)}</strong> · ${esc(w.zh)}</p></div><button data-act="next">${S.index+1>=S.round.length||S.lives===0?"看结果":"下一题 →"}</button></div>`:"";return `<div class="shell game-shell"><div class="game-top"><button data-act="home">← 退出</button><div class="round-progress"><i style="width:${progress}%"></i></div><span>${S.index+1} / ${S.round.length}</span><b>🔥 ${S.streak}</b><strong>${"♥".repeat(S.lives)}<i>${"♥".repeat(3-S.lives)}</i></strong></div><section class="game-card ${S.feedback}"><span class="stage">${modes.find(m=>m.id===S.mode).title}</span><h2>${prompt}</h2>${task}${opts}${fb}</section><div class="game-score"><span>SCORE</span><b>${S.score}</b><small>准确率 ${Math.max(0,accuracy)}%</small></div></div>`}
function modal(){return S.showImport?`<div class="modal-back"><div class="modal"><button class="modal-x" data-act="close">×</button><span class="eyebrow">家长设置</span><h2>粘贴新单词</h2><p>每行一个，英文和中文之间用逗号、Tab 或冒号分隔。建议 20–40 个。</p><textarea id="draft" placeholder="apple, 苹果\nborrow, 借入\ncareful, 小心的"></textarea><div class="modal-foot"><span>已识别 <b id="count">0</b> 个</span><button id="saveWords" data-act="saveWords" disabled>保存并开始</button></div></div></div>`:""}
function render(){app.innerHTML=header()+(S.view==="home"?home():S.view==="words"?wordList():game())+modal();bind();if(S.view==="game"&&S.mode==="spell"&&!S.feedback)document.querySelector("#spell")?.focus()}
function start(mode){const ranked=[...S.words].sort((a,b)=>(b.mistakes-a.mistakes)||(a.mastered-b.mastered)),weak=shuffle(ranked.slice(0,Math.min(80,ranked.length))).slice(0,7),fresh=shuffle(S.words.filter(w=>!weak.includes(w))).slice(0,3);S.round=shuffle([...weak,...fresh]).slice(0,Math.min(10,S.words.length));Object.assign(S,{mode,index:0,score:0,streak:0,lives:3,feedback:"",answer:"",view:"game"});S.choices=choices(S.round[0],mode);render();if(mode==="listen")setTimeout(()=>speak(cur().en),300)}
function mark(ok){if(S.feedback)return;const w=cur();S.feedback=ok?"right":"wrong";if(ok){S.score+=100+Math.min(S.streak,5)*20;S.streak++;S.best=Math.max(S.best,S.streak);speak(w.en)}else{S.streak=0;S.lives=Math.max(0,S.lives-1)}S.words=S.words.map(x=>x.en===w.en?{...x,mastered:Math.max(0,x.mastered+(ok?1:0)),mistakes:x.mistakes+(ok?0:1)}:x);save();render()}
function next(){S.index++;if(S.index>=S.round.length||S.lives===0){S.view="home";render();return}S.feedback="";S.answer="";S.choices=choices(cur(),S.mode);render();if(S.mode==="listen")setTimeout(()=>speak(cur().en),250)}
function action(a){if(a==="home"||a==="words"){S.view=a;S.showImport=false;render()}else if(a==="sound"){S.soundOn=!S.soundOn;render()}else if(a==="quick")start(modes[Math.floor(Math.random()*modes.length)].id);else if(a==="import"){S.showImport=true;render()}else if(a==="close"){S.showImport=false;render()}else if(a==="spell")mark((document.querySelector("#spell")?.value||"").trim().toLowerCase()===cur().en.toLowerCase());else if(a==="readDone")mark(true);else if(a==="next")next();else if(a==="saveWords"){const p=parseWords(document.querySelector("#draft").value);if(p.length>=4){S.words=p;S.showImport=false;S.view="home";save();render()}}}
function bind(){document.querySelectorAll("[data-act]").forEach(x=>x.onclick=()=>action(x.dataset.act));document.querySelectorAll("[data-mode]").forEach(x=>x.onclick=()=>start(x.dataset.mode));document.querySelectorAll("[data-speak]").forEach(x=>x.onclick=()=>speak(x.dataset.speak));document.querySelectorAll("[data-choice]").forEach(x=>x.onclick=()=>mark(x.dataset.choice===cur().en));const spell=document.querySelector("#spell");if(spell){spell.oninput=e=>S.answer=e.target.value;spell.onkeydown=e=>{if(e.key==="Enter")action("spell")}}const draft=document.querySelector("#draft");if(draft)draft.oninput=e=>{const n=parseWords(e.target.value).length;document.querySelector("#count").textContent=n;document.querySelector("#saveWords").disabled=n<4}}
render();
